### ISSUE TITLE
multiple ajax requests

### ISSUE THREAD

**Issue by ms88privat** [voronianski/ngprogress-lite#16]
Hello, nice plugin!

In my case i do an normal ajax request to get some collection data from the server and furthermore an geolocation.getCurrentPosition request.

The progress should only reach 100% if both of them are done. 

At the moment, i start and end every ajax request with a progress-bar, so i don't have to handle everything for myself every time again. For the currentPostionen request i have to start a "second" progress-bar. This resolves into one correct progress (short ajax request) and after that the second "done()" (position) kicks in and shows up for a short amount of time. 

The plugin should add up progresses and resolve them only if all off them are resolved.

Thank you very much
Marcel

**Comment by AidasK** [comment]
For this I have created a simple buffer, which calls automatically `done` once all promises are resolved.
```js
angular.module('app.services').factory('progress',
function($q, ngProgressLite) {
    var loading;
    var promises = [];
    var last;
    function goOn(final) {
        if (!promises.length) {
            if (final === true) {
                ngProgressLite.done();
                last = null;
            } else {
                // small buffer, in case something starts to load
                setTimeout(function () {
                    goOn(true);
                }, 0);
                ngProgressLite.inc();
            }
        } else {
            ngProgressLite.inc();
            last = promises.pop().then(goOn, goOn);
        }
    }

    /**
     * @name progress
     */
    var progress = {
        loadingStart: function () {
            if (loading) {
                return ;
            }
            loading = $q.defer();
            progress.loading(loading.promise);
        },
        loadingDone: function () {
            loading && loading.resolve();
            loading = null;
        },
        loading: function (promise) {
            if (!last) {
                ngProgressLite.start();
                last = promise.then(goOn, goOn);
            } else {
                promises.push(promise);
            }
        }
    };
    return progress;
});
```

Usage:
```js
progress.loading($http.get(...));
progress.loading($http.get(...));
```
