### ISSUE TITLE
Position, any help?

### ISSUE THREAD

**Issue by maeishoj** [voronianski/ngprogress-lite#23]
Is it possible to have this progress bar appearing into a specific div?

How would you go about it?

Appreciate it.

**Comment by voronianski** [comment]
@maeishoj you can use your own template, see https://github.com/voronianski/ngprogress-lite#configuration

e.g. - https://github.com/voronianski/ngprogress-lite/blob/master/ngprogress-lite.js#L31

**Comment by maeishoj** [comment]
@voronianski  I understand making a template for it, but I was wondering more about placing it into an existing div.

**Comment by voronianski** [comment]
@maeishoj there's no such possibility for now.

**Comment by maeishoj** [comment]
Oh I thought. I tried angular-load as well and I even tried to use jquery to append the containing div to another div, but didn't work :P . Oh well.. :/ too bad..
