### ISSUE TITLE
How can I change the color of progress bar ?

### ISSUE THREAD

**Issue by mukulgupta2507** [voronianski/ngprogress-lite#24]
Hi,

I want to change the default color of progress bar. Is there any way by which I can do that ?

Thanks

**Comment by voronianski** [comment]
@mukulgupta2507 it's just css: 

- https://github.com/voronianski/ngprogress-lite#customization
- https://github.com/voronianski/ngprogress-lite/blob/master/ngprogress-lite.css#L6
